### ISSUE TITLE
Windows version needed

### ISSUE THREAD

**Issue by bizzbyster** [virtuallynathan/qpep#4]
I would like to use Qpep as an accelerator of satellite connections when connected via a software client VPN. See https://docs.projectfaster.org/use-cases/vpn-over-satellite/vpn-client-software/optimizing-client-software for a picture. To do this, I need a version that runs on Windows since most corporate VPN users are running Windows. Running a Go client on Windows is no problem so this is mostly about the UI, the connection redirection, and the installer. Open source [VpnHood](https://github.com/vpnhood/VpnHood) does this the right way using the open source [WinDivert](https://reqrypt.org/windivert.html) redirecting TCP connections to the client running on the end user's Windows machine.

Definition of done: a build of qpep creates an installer package that can be run on the latest versions of Windows that will use WinDivert to redirect connections from any application (including SMB on Windows for remote file sharing) destined for a remote address to the local qpep client, which will then use QUIC to tell the QPEP server to open a connection to the remote destination server. The TCP payload data sent on the application connection should be sent to the remote QPEP server as soon as it is received -- not waiting for an acknowledgement that the remote TCP connection between QPEP server and content server has been established.

**Comment by parvit** [comment]
@bizzbyster Hi, i've started working on this, i would like to ask what exactly do you intend with "so this is mostly about the UI". I don't seem to have seen any UI in this tool.

Maybe you intended the installer UI? Please clarify.

At the moment i'm exploring the C side of WinDivert to understand exactly how to make it do what you ask but it seems to already have all the pieces so i'm not too worried.

My branch is at https://github.com/parvit/qpep/tree/qpep-win, i'll update as soon as i have further questions / progress.

**Comment by bizzbyster** [comment]
My comment about the UI was unclear. I think it is mostly about redirection. The UI should simply let me enable and disable the redirection. Does that help?

**Comment by parvit** [comment]
@bizzbyster Thank you, I think i understand what you say, would it be acceptable if this UI was an icon in the tray with a menu to enable / disable the redirection?

**Comment by bizzbyster** [comment]
Sounds good -- thanks!

**Comment by mfoxworthy** [comment]
The app should also have a tray icon allowing the user to see that the vpn/pep is active.

**Comment by bizzbyster** [comment]
Agreed

**Comment by parvit** [comment]
Hi everyone, i've managed in my branch to (partially) complete the redirect from local connection to the client and then to the qpep server.

However i think i'm missing a piece of the puzzle: how does the qpep server know the original destination of the packet so it can send it to the outside network?

I should give an example:
1) i open a netcat to a remote server, lets say google, on port 8080 
2) my qpep client is running locally on port 9443
3) the packets from netcat 8080 are redirected to 9443
4) qpep client opens the connection to the qpep server and it receives the data

At this point how does the server know to contact the original google server?
Thank you for the help.

**Comment by parvit** [comment]
Nevermind i documented better about QUIC so now I understand better and made it work.

Now only 4 things remain to complete everything that was asked:
- [x] Handling of FIN / RST in the diverter
- [x] Finish the tray icon integration
- [x] Finish the additional data (text/images) in the installer
- [x] Docs of the native windiverter integration

**Comment by parvit** [comment]
@bizzbyster Hi, i've finished the development, i'll post the PR in a short while.

**Comment by parvit** [comment]
@bizzbyster @virtuallynathan 
Hi, is there a timeline for closing the issue? Can i help?

**Comment by bizzbyster** [comment]
Testing and code reviewing now. Sorry for slowness.

**Comment by parvit** [comment]
No problem, if you have any doubts i'm available.

**Comment by bizzbyster** [comment]
@parvit this is impressive work. We are code reviewing and testing. Hope its ok if we take another day before rewarding the bountysource bounty.

**Comment by bizzbyster** [comment]
@parvit do you want to update the readme with instructions for building the windows client?

**Comment by parvit** [comment]
@bizzbyster Sure i'm modifying it right now.

**Comment by mfoxworthy** [comment]
I have a few questions regarding PR #5.

@virtuallynathan - I saw the addition of The Clear BSD License. I'm not sure what is going on upstream aside from the fact that QUIC-GO uses an MIT license. Are we obligated to mention that in the distribution? I am asking you because the license file if referring to you as the licensor.

@parvit - This is using go 1.16.x. Any reason we didn't use 1.18.x? Is there a library you are using that hasn't updated yet? I ask because I had previously updated to 1.17.x and was hoping to move to 1.18.x. Thanks for the build instruction for Windoze. We are building and testing right now.

**Comment by parvit** [comment]
@mfoxworthy Hi it is not related to my change (i don't think it has any strict dependency on go version), if you try to compile the current qpep with go 1.17.3 for example you can compile it but not run it.

```
$ .\qpep.exe --client
panic: qtls.CertificateRequestInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-16.init.0()
        C:/home/dev/pkg/mod/github.com/marten-seemann/qtls-go1-16@v0.1.3/unsafe.go:17 +0x198
```

That package `github.com/marten-seemann/qtls-go1-16` was not updated for following go versions so i thought of including that bit of info for anyone else that tries to compile it.

Also for the BSD License question it is the license of the WinDivert library, i'm no legal expert so i don't know if the two are compatible and how to handle it but i think it should be included.

**Comment by mfoxworthy** [comment]
@parvit Yes, I agree with you. After a second look I see that QUIC-GO is at 1.16. I do recall compiling with 1.17 with a local QUIC-GO that I upgraded to 1.17. I was confused. I think we should find out how it should be licensed because the original work was MIT licensed. As long as we didn't make changes to WinDivert, I believe we can redistribute by referencing the WinDivert license in the build directory.

**Comment by parvit** [comment]
Yes, no changes were made to the library, at the moment the WinDivert license is copied and installed as LICENSE.windivert so that in the installed directories there are both license files.

However there is no simple way of adding two license confirmations in the installer so only the QPep main license is shown and accepted.

If you think appropriate we could also add the windivert license to that step of the installer (as a single document) and the user would have to accept both.

**Comment by mfoxworthy** [comment]
> Yes, no changes were made to the library, at the moment the WinDivert license is copied and installed as LICENSE.windivert so that in the installed directories there are both license files.
> 
> However there is no simple way of adding two license confirmations in the installer so only the QPep main license is shown and accepted.
> 
> If you think appropriate we could also add the windivert license to that step of the installer (as a single document) and the user would have to accept both.

That could work as well. We can just specify which license covers which component and add them both. I don't think there are legal boundaries on how we inform the user, we just need to inform them.

**Comment by parvit** [comment]
@mfoxworthy ok, later i'll change the RTF file to contain both licenses.

**Comment by parvit** [comment]
@mfoxworthy License change is included in pull #6

**Comment by nachocardozop** [comment]
Hi @parvit you can go ahead and claim the issue as complete in Bountysource (I will approve it) - please just continue to answer @bizzbyster and @mfoxworthy 's questions as they finish evaluating your code (should be done by Monday or Tuesday). Thanks!!

**Comment by parvit** [comment]
@nachocardozop Sure, I'll respond to any question, you can also reach me directly via mail anytime.

If i have the time available ( or you get another bounty out ;) ) i'll gladly work again on this interesting project.

EDIT: The issue needs to be closed to allow me to claim the bounty

**Comment by bizzbyster** [comment]
Great work @parvit !! We will report issues as we continue our testing.

**Comment by parvit** [comment]
Thank you, i'm available if you neeed anything else.
